export enum QueryResponseType {
    Text = 'Text',
    Float = 'Float',
    Integer = 'Integer',
    Boolean = 'Boolean',
    Object = 'Object',
    TextArray = 'TextArray',
    SingleChoiceSelection = 'SingleChoiceSelection',
    MultiChoiceSelection = 'MultiChoiceSelection',
    File = 'File',
    Date = 'Date',
    DateTime = 'DateTime',
    Rating = 'Rating',
    Location = 'Location',
    Url = 'Url',
    Range = 'Range',
}
