// Field Response Types
export enum FieldResponseType {
    Text = 'Text',
    Number = 'Number',
    Boolean = 'Boolean',
    Date = 'Date',
    DateTime = 'DateTime',
    Time = 'Time',
    Email = 'Email',
    Phone = 'Phone',
    URL = 'URL',
    Password = 'Password',
    TextArea = 'TextArea',
    Select = 'Select',
    MultiSelect = 'MultiSelect',
    Radio = 'Radio',
    Checkbox = 'Checkbox',
    File = 'File',
    Image = 'Image',
    Signature = 'Signature',
    Location = 'Location',
    Rating = 'Rating',
    Slider = 'Slider',
    Color = 'Color',
    RichText = 'RichText',
    JSON = 'JSON',
}
