# Required secrets
# SERVER_HOST
# SERVER_PORT
# SERVER_USER
# SERVER_SSH_KEY
# SERVER_PASSPHRASE

name: Continuous Deployment to Server

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'
        required: true
      ecr_registry_uri:
        description: 'ECR registry URI'
        required: true
      ecr_repository_name:
        description: 'ECR repository name'
        required: true
      ecr_image_tag:
        description: 'Image tag to deploy'
        required: true

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        passphrase: ${{ secrets.SERVER_PASSPHRASE }}
        script: |
          set -e
          SERVICE_NAME="${{ github.event.inputs.service }}"
          ECR_REGISTRY_URI="${{ github.event.inputs.ecr_registry_uri }}"
          ECR_REPOSITORY_NAME="${{ github.event.inputs.ecr_repository_name }}"
          ECR_IMAGE_TAG="${{ github.event.inputs.ecr_image_tag }}"

          ECR_IMAGE=${ECR_REGISTRY_URI}/${ECR_REPOSITORY_NAME}:${ECR_IMAGE_TAG}

          echo "Pulling latest image $ECR_IMAGE..."
          docker pull $ECR_IMAGE

          COMPOSE_FILE="./webservices/forms-dev/compose/docker-compose.yml"

          echo "Updating image for $SERVICE_NAME in $COMPOSE_FILE..."
          # Replace image line under the selected service
          sed -i "/^[[:space:]]*$SERVICE_NAME:/,/^[[:space:]]*[a-zA-Z]/s|^[[:space:]]*image:.*|    image: $ECR_IMAGE|" $COMPOSE_FILE

          echo "Redeploying $SERVICE_NAME..."
          docker compose -f $COMPOSE_FILE up -d $SERVICE_NAME

          echo "Deployment successful"
